### ISSUE TITLE
did you inscribe all of these yourself?

### ISSUE THREAD

**Issue by skyrover7** [dannydeezy/ordmojis#1]
amazing! nicely done!

**Comment by dannydeezy** [comment]
thank you! i inscribed a few good ones for myself (had the advantage of a little headstart)
but even before i ever thought of this, several emojis had been inscribed like heart, clown, etc

**Comment by skyrover7** [comment]
haha nice! any plans on what you'll do with them?

**Comment by skyrover7** [comment]
ok i found ordmoji discord! haha
